# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "nfss01" do |nfss01|
    nfss01.vm.network "private_network", ip: "192.168.50.20", virtualbox__intnet: "net1"
    nfss01.vm.hostname = "nfss01.otus.test"
#    nfss01.vm.provision "shell", path: "nfss01_script.sh"
  end

  config.vm.define "nfsc01" do |nfsc01|
    nfsc01.vm.network "private_network", ip: "192.168.50.21", virtualbox__intnet: "net1"
    nfsc01.vm.hostname = "nfsc01.otus.test"
#    nfsc01.vm.provision "shell", path: "nfsc01_script.sh"
  end

  config.vm.define "krb" do |krb|
    krb.vm.network "private_network", ip: "192.168.50.22", virtualbox__intnet: "net1"
    krb.vm.hostname = "krb.otus.test"
#    krb.vm.provision "shell", path: "krb_script.sh"
  end

 config.vm.provision :hosts do |provisioner|
    provisioner.add_host '192.168.50.20', ['nfss01.otus.test']
    provisioner.add_host '192.168.50.21', ['nfsc01.otus.test']
    provisioner.add_host '192.168.50.22', ['krb.otus.test']
  end

end

