# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :pam => {
        :box_name => "centos/7"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: "192.168.60.10"
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
                                                                                                     
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
          box.vm.provision "shell", path: "pam.sh"
      end
  end
end
