# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "vmsystmd" do |vmsystmd|
    vmsystmd.vm.box = "centos/7"
    vmsystmd.vm.hostname = 'vmsystmd'
    vmsystmd.vm.box_url = "centos/7"
    vmsystmd.vm.network "public_network", type: "dhcp"
end
end
